### PR TITLE
fixing worker probes

### PR DESCRIPTION
**Pull request by deepak1725**
GT Worker is not exposing any Endpoint. Falling Back to another method of Probing

### CODE REVIEW

**Comment by vinaybommana** [comment]
``Hi @deepak1725, I'm assuming the web-app will create this `/tmp/healthy` when it is ready to accept requests or is this just a file which is always true ?
```
                  command:
                    - cat
                    - /tmp/healthy
```

also there is `glitchtip-beat` deployment which is also checking for the `GT_APP_PORT`, should we change the readiness and liveness here as well ?

**Comment by deepak1725** [comment]
> Hi @deepak1725, I'm assuming the web-app will create this `/tmp/healthy` when it is ready to accept requests or is this just a file which is always true ?
> 
> ```
>                   command:
>                     - cat
>                     - /tmp/healthy
> ```
> 
> also there is `glitchtip-beat` deployment which is also checking for the `GT_APP_PORT`, should we change the readiness and liveness here as well ?

As per Docs https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes , when you are able to execute `cat` command, your Pod is ready. 

Regarding `beat` will see in next PR. This is specific to worker only

**Comment by vinaybommana** [comment]
@pepedocs What do you think ?

**Comment by pepedocs** [comment]
@deepak1725 Can you add how this is going to work?

**Comment by deepak1725** [comment]
> @deepak1725 Can you add how this is going to work?

https://github.com/rh-cssre/glitchtip-frontend/pull/64#issuecomment-1129658090

**Review by Nanyte25 — APPROVED** [review]
@deepak1725 I approve the removal for the readiness and liveness probes for now but we will have to figure how to enable them once the app front-end is decoupled from its backend work is completed.

**Pull request merged**
