### PR TITLE
version change for node due to dependency packages

### PR DESCRIPTION
**Pull request by vinaybommana**
#### What:
we are facing errors in CI for unit-tests due to failed dependency resolution
```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from ngx-markdown@13.1.0
npm ERR! node_modules/ngx-markdown
npm ERR!   ngx-markdown@"^13.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@13.3.11
```
this is due to node version we are using which is `16.x`

I've modified the node version to `14.x`

### CODE REVIEW

**Comment by vinaybommana** [comment]
the [upstream](https://gitlab.com/glitchtip/glitchtip-frontend/-/blob/master/.gitlab-ci.yml) project is using `node: 16` and `npm ci --force` for ignoring dependencies.. for simplicity modified the github action to the same.

**Review by pepedocs — APPROVED** [review]
I think this won't cause any issues because so far we use upstream npm packates, if there is an update in there, we also update ours. In the case where we need to use a different package than the upstream, then that's where we need to have a look - However I think we must discourage this variation to keep things simple.

**Review by Nanyte25 — APPROVED** [review]
@vinaybommana I am happy to approve this for now, have we consulted with the upstream maintainer of Glitchtip, how they are handling this? It would be great to add their comments for historical purposes to this git conversation.

**Comment by vinaybommana** [comment]
Thanks @Nanyte25 @pepedocs, I've not consulted the upstream maintainer.. however I see the recent commits they did regarding the CI in gitlab, they are adding `npm ci --force` for checks
ref: https://gitlab.com/glitchtip/glitchtip-frontend/-/commit/12b808af6f1bbb3d6bd9e0a8d22c394d68881751

**Pull request merged**
